### PR TITLE
Include option to install via terminus

### PR DESCRIPTION
**Pull request by tekNorah**

### CODE REVIEW

**Review by uberhacker — CHANGES_REQUESTED** [review]
Thank you for the update @tekNorah!  See https://github.com/pantheon-systems/terminus-plugin-example#installation for the suggested instructions.

**Comment by philoSurfer** [comment]
@uberhacker I think the call out here is to update the local docs for the plugin as the namespace is a little different from the other officially managed Pantheon Terminus plugins. 

I have had to share this specific command a couple of times as people have had a struggle trying to get it to install.

**Comment by uberhacker** [comment]
@philoSurfer: There is nothing wrong with adding this to avoid confusion.  I was just pointing out there is a distinction from the latest Terminus 3 instructions versus the older Terminus 2 instructions.  It should be noted for each version.

**Comment by uberhacker** [comment]
@derimagia: Anything to add here?

**Comment by philoSurfer** [comment]
updated with a new PR here:
https://github.com/terminus-plugin-project/terminus-pancakes-plugin/pull/37

**Comment by uberhacker** [comment]
Fixed in #37.

**Comment by tekNorah** [comment]
@philoSurfer @uberhacker  😢 awww... now I don't get credit... lol, jk, glad I could help prompt for a change here!

**Pull request closed without merging**
