### PR TITLE
Terminus 1.x Version Update

### PR DESCRIPTION
**Pull request by sean-e-dietrich**
Rewrote the plugin to work with 1.x and kept the same three applications available.

### CODE REVIEW

**Comment by derimagia** [comment]
Nice! Been meaning to do this. The link to the docs was for installing, so it probably should be changed to `https://pantheon.io/docs/terminus/plugins/` since that has instructions there.

I'll take a look at this later to merge it - I think I'll need to make a release for 0.13 first

Thanks for your work

**Comment by sean-e-dietrich** [comment]
I agree. I probably thought it may have been better in general to link to the Terminus page, but the plugin page sounds like a much better place.

**Comment by sean-e-dietrich** [comment]
I need to close this pull request. I realize that not testing before hand there was a small issue with one of the plugins and need to create a new pull request.

**Comment by derimagia** [comment]
Thanks for your work! Released Pancakes 0.1 for Terminus 0.13 - https://github.com/derimagia/terminus-pancakes/releases/tag/0.1

**Pull request merged**
